

Profiles:

    TwoOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *car
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *baoma
                    - *benchi
                    - *falali
                   
                    # - *Org3
                    # - *Org4
                    # - *Org5
    TwoOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *baoma
                - *benchi
                - *falali
                # - *Org3
                # - *Org4
                # - *Org5

Organizations:

    - &car
        Name: carMSP
        ID: carMSP
        MSPDir: crypto-config/ordererOrganizations/car.com/msp

    - &baoma
        Name: baomaMSP
        ID: baomaMSP

        MSPDir: crypto-config/peerOrganizations/baoma.car.com/msp

        AnchorPeers:
            - Host: peer0.baoma.car.com
              Port: 7051

    - &benchi
        Name: benchiMSP
        ID: benchiMSP

        MSPDir: crypto-config/peerOrganizations/benchi.car.com/msp

        AnchorPeers:
            - Host: peer0.benchi.car.com
              Port: 7051


    - &falali
        Name: falaliMSP
        ID: falaliMSP

        MSPDir: crypto-config/peerOrganizations/falali.car.com/msp

        AnchorPeers:
            - Host: peer0.falali.car.com
              Port: 7051

    # - &Org3
    #     Name: Org3MSP
    #     ID: Org3MSP

    #     MSPDir: crypto-config/peerOrganizations/org3.car.com/msp

    #     AnchorPeers:
    #         - Host: peer0.org3.car.com
    #           Port: 7051

    # - &Org4
    #     Name: Org4MSP
    #     ID: Org4MSP

    #     MSPDir: crypto-config/peerOrganizations/org4.car.com/msp

    #     AnchorPeers:
    #         - Host: peer0.org4.car.com
    #           Port: 7051

    # - &Org5
    #     Name: Org5MSP
    #     ID: Org5MSP

    #     MSPDir: crypto-config/peerOrganizations/org5.car.com/msp

    #     AnchorPeers:
    #         - Host: peer0.org5.car.com
    #           Port: 7051

Orderer: &OrdererDefaults

    OrdererType: kafka

    Addresses:
        - car0.car.com:7050
        - car1.car.com:7050
        - car2.car.com:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 98 MB

        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 39.105.37.84:9092
            - 39.105.83.126:9092
            - 47.94.169.105:9092
            - 39.105.17.149:9092

    Organizations:

Application: &ApplicationDefaults

    Organizations:

Capabilities:
    Global: &ChannelCapabilities
        V1_1: true

    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_1: true