Organizations:

    - &audi
        Name: audiMSP
        ID: audiMSP

        MSPDir: crypto-config/peerOrganizations/audi.car.com/msp

        AnchorPeers:
            - Host: peer0.audi.car.com
              Port: 7051